// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using day03.Data;

#nullable disable

namespace day03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("day03.Models.StudentScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ScoreId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentScore", (string)null);

                    b.HasData(
                        new
                        {
                            ScoreId = 1,
                            Score = 8.00m,
                            StudentId = "STD001",
                            StudentName = "Alex Tran",
                            SubjectId = "SUB001"
                        },
                        new
                        {
                            ScoreId = 2,
                            Score = 7.50m,
                            StudentId = "STD001",
                            StudentName = "Alex Tran",
                            SubjectId = "SUB002"
                        },
                        new
                        {
                            ScoreId = 3,
                            Score = 9.00m,
                            StudentId = "STD002",
                            StudentName = "Tai Pham",
                            SubjectId = "SUB001"
                        },
                        new
                        {
                            ScoreId = 4,
                            Score = 4.00m,
                            StudentId = "STD003",
                            StudentName = "Alice Nguyen",
                            SubjectId = "SUB003"
                        },
                        new
                        {
                            ScoreId = 5,
                            Score = 7.00m,
                            StudentId = "STD003",
                            StudentName = "Alice Nguyen",
                            SubjectId = "SUB002"
                        });
                });

            modelBuilder.Entity("day03.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subject", (string)null);

                    b.HasData(
                        new
                        {
                            SubjectId = "SUB001",
                            SubjectName = "C# Programming"
                        },
                        new
                        {
                            SubjectId = "SUB002",
                            SubjectName = "SQL Server Database"
                        },
                        new
                        {
                            SubjectId = "SUB003",
                            SubjectName = "ASP.NET Core MVC Web App"
                        });
                });

            modelBuilder.Entity("day03.Models.StudentScore", b =>
                {
                    b.HasOne("day03.Models.Subject", "Subject")
                        .WithMany("StudentScores")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("day03.Models.Subject", b =>
                {
                    b.Navigation("StudentScores");
                });
#pragma warning restore 612, 618
        }
    }
}
