// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using day03.Models.Data;

#nullable disable

namespace day03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260728094950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("day03.Models.StudentScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ScoreId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentScore");

                    b.HasData(
                        new
                        {
                            ScoreId = 1,
                            Score = 8.5m,
                            StudentId = "SV001",
                            StudentName = "Nguyễn Văn A",
                            SubjectId = "SUB01"
                        },
                        new
                        {
                            ScoreId = 2,
                            Score = 9.0m,
                            StudentId = "SV002",
                            StudentName = "Trần Thị B",
                            SubjectId = "SUB02"
                        },
                        new
                        {
                            ScoreId = 3,
                            Score = 7.5m,
                            StudentId = "SV003",
                            StudentName = "Lê Văn C",
                            SubjectId = "SUB03"
                        });
                });

            modelBuilder.Entity("day03.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            SubjectId = "SUB01",
                            SubjectName = "C#"
                        },
                        new
                        {
                            SubjectId = "SUB02",
                            SubjectName = "ASP.NET Core"
                        },
                        new
                        {
                            SubjectId = "SUB03",
                            SubjectName = "SQL Server"
                        });
                });

            modelBuilder.Entity("day03.Models.StudentScore", b =>
                {
                    b.HasOne("day03.Models.Subject", "Subject")
                        .WithMany("StudentScore")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("day03.Models.Subject", b =>
                {
                    b.Navigation("StudentScore");
                });
#pragma warning restore 612, 618
        }
    }
}
